security:

    providers:
        Facebook:
            id: Facebook

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    firewalls:
        main:
            anonymous: ~
            stateless: true
            guard:
                authenticators:
                    - AppBundle\Security\TokenAuthenticator






