# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
            Facebook:
                id: AppBundle\Security\User\FacebookUserProvider

    firewalls:

        main:
            anonymous: ~
            logout: ~
            guard:
                authenticators:
                    - AppBundle\Security\TokenAuthenticator
        # disables authentication for assets and the profiler, adapt it according to your needs
        #dev:
            #pattern: ^/(_(profiler|wdt)|css|images|js)/
            #security: false

