parameters:


services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    Facebook:
        class: AppBundle\Security\FacebookUserProvider
        arguments: ["@csa_guzzle.client.Facebook_graph", "@jms_serializer","@doctrine.orm.entity_manager"]

    CodeManager:
        public: true
        class: AppBundle\Service\CodeManager
        arguments: ["%api_id%", "%api_key%"]

    Validator_service:
        public: true
        class: AppBundle\Service\Validator
        arguments: ['@validator']
